# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2wSuPbjWttsJ6nhf6lsRhIaEk1Ac-6C
"""

x=10
seq="ATCGTA"

pip install biopython

from Bio import SeqIO
seq=(">ATCGTGCGTA")
for seq in SeqIO.parse("seq","fasta"):
                                      print("seq",seq)

from Bio.Seq import Seq
seq=Seq("ATGCGTATGC")
print("seq",seq)

from Bio.SeqUtils import gc_fraction
Seq="ATGCGTGCGTGCGCGCGTGCGTATAT"
print("GC Content",gc_fraction(Seq))

from Bio.Seq import Seq
DNA=Seq("ATGCGTTGCGCGCGTAATATTTA")
RNA=DNA.transcribe()
print("RNA",RNA)

from Bio.Seq import Seq
DNA=Seq("ATGCCGTGCGTATGCGTAATGCGTGCGATGCGCGTGCGTATATGCGCTA")
protein=DNA.translate()
print("protein",protein)

from Bio.Seq import Seq
dna=Seq("ATGCGCGTAGACGTGACGT")
print("reverse complement",dna.reverse_complement)

from Bio.Seq import Seq
dna=Seq("ATGCGCGTAATGCGTA")
for base in "ATGC":print(base,"=",dna.count(base))