# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUBSy4DWlD8CbCGG74nBrTcRwKLbz_3E
"""

!pip install fair-esm biopython

import torch
import esm
import numpy as np
from Bio import SeqIO

model, alphabet = esm.pretrained.esm2_t6_8M_UR50D()
model = model.eval().cuda() if torch.cuda.is_available() else model.eval()
batch_converter = alphabet.get_batch_converter()

sequence = """MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAED
LQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN"""
data = [("protein1", sequence)]
batch_labels, batch_strs, batch_tokens = batch_converter(data)
if torch.cuda.is_available():
    batch_tokens = batch_tokens.cuda()

with torch.no_grad():
    results = model(batch_tokens, repr_layers=[6])
token_representations = results["representations"][6]

protein_embedding = token_representations.mean(1).cpu().numpy()
protein_embedding.shape

# ---------------------------------------------------------
# 3D STRUCTURE PREDICTION USING ESMFold
# ---------------------------------------------------------

!pip install fair-esm py3Dmol

import torch
from esm import pretrained
import py3Dmol

# Load ESMFold model
fold_model = pretrained.esmfold_v1()
if torch.cuda.is_available():
    fold_model = fold_model.cuda()
fold_model = fold_model.eval()

sequence_clean = sequence.replace("\n", "").strip()

# Predict PDB structure
with torch.no_grad():
    pdb_output = fold_model.infer_pdb(sequence_clean)

# Save PDB file
with open("predicted_structure.pdb", "w") as f:
    f.write(pdb_output)

print("🎉 PDB saved successfully as predicted_structure.pdb")

# toy classifier
weight = np.random.randn(320)
bias = np.random.randn()

score = protein_embedding.dot(weight) + bias
prob = 1 / (1 + np.exp(-score))

if prob > 0.5:
    print("🔥 Predicted: Enzyme (prob =", round(prob, 3), ")")
else:
    print("🧊 Predicted: Non-Enzyme (prob =", round(prob, 3), ")")

import numpy as np

# toy classifier
weight = np.random.randn(320)
bias = np.random.randn()

score = protein_embedding.dot(weight) + bias
prob = 1 / (1 + np.exp(-score))

# convert numpy float -> Python float
prob_scalar = float(prob)

if prob_scalar > 0.5:
    print("🔥 Predicted: Enzyme (prob =", round(prob_scalar, 3), ")")
else:
    print("🧊 Predicted: Non-Enzyme (prob =", round(prob_scalar, 3), ")")

pdb_string = model.generate()   # <-- whatever gives you your predicted PDB text

with open("predicted_structure.pdb", "w") as f:
    f.write(pdb_string)

print("PDB saved as predicted_structure.pdb")

pdb = open("predicted_structure.pdb").read()

view = py3Dmol.view(width=600, height=450)
view.addModel(pdb, "pdb")
view.setStyle({"cartoon": {"color": "spectrum"}})
view.zoomTo()
view.show()